In [1]:
import numpy as np

In [11]:
a =np.array([[64,32],[31,0],[49,46],[0,0]])
a

array([[64, 32],
       [31,  0],
       [49, 46],
       [ 0,  0]])

In [12]:
a.shape

(4, 2)

In [15]:
a.ndim

2

In [16]:
a.itemsize

4

In [21]:
# Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
a =np.arange(100,200,10).reshape(5,2)
a


array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [27]:
#Following is the provided numPy array. Return array of items by taking the third column from all rows
a =np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
a
a1 = a[...,2]
a1

array([33, 66, 99])

In [46]:
# Return array of odd rows and even columns from below numpy array
a = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
a

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [74]:
a[::2][:3,1::2]

        

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [81]:
#Create a result array by adding the following two NumPy arrays.
#Next, modify the result array by calculating the square of each element
a =  np.array([[5, 6, 9], [21 ,18, 27]])
b = np.array([[15 ,33, 24], [4 ,7, 1]])
c = np.array([a[0]+b[0],a[1]+b[1]])
c

array([[20, 39, 33],
       [25, 25, 28]])

In [94]:

d= np.square(c)
d

array([[-679215104, 1920038660, -772684796],
       [ 466206468,  466206468, -620494848]], dtype=int32)

In [4]:
#Write a NumPy program to create a null vector of size 10 and update sixth value to 11
a =np.zeros(10, dtype = int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
a[6] =11
a

array([ 0,  0,  0,  0,  0,  0, 11,  0,  0,  0])

In [19]:
# Write a NumPy program to create an array with values ranging from 12 to 38.
a = np.arange(12,38)
a
    

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [21]:
#Write a NumPy program to reverse an array 
a[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [26]:
#Write a NumPy program to create a 2d array with 1 on the border and 0 inside
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
# Write a NumPy program to add a border (filled with 0's) around an existing array.
a[0:5]=0
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
# Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern
b = np.ones((3,3),dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [52]:
# Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern
b = np.zeros((8,8),dtype = int)
b

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [68]:
b[1::2,::2]=1
b[::2,1::2]=0
b

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [70]:
#Write a NumPy program to convert a list and tuple into arrays.
a = np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
#Write a NumPy program to create an empty and a full array.
a = np.empty((4,3))
a

array([[1.14877376e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.16709769e-312, 4.66000113e-033],
       [2.14579425e+184, 1.71802573e+185, 3.80286251e+175],
       [1.10502145e+165, 5.24261269e+174, 2.04122676e+184]])

In [75]:
b = np.full((3,3),6)
b

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [80]:
#Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees and vice versa. 
x = [0, 12, 45.21, 34, 99.91]
f = np.array(x)
print('value in Fahrenheit degrees:',f)
d = 5*f/9-5*32/9
c = np.round((d),2)
print('value in centigrate degrees:',c)


value in Fahrenheit degrees: [ 0.   12.   45.21 34.   99.91]
value in centigrate degrees: [-17.78 -11.11   7.34   1.11  37.73]


In [87]:
#Write a NumPy program to find the real and imaginary parts of an array of complex numbers.
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print(x.real)
print(y.real)
print(x.imag)
print(y.imag)

[1.]
[0.70710678]
[0.]
[0.70710678]


In [92]:
#Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
a1 = np.array([10,20,30,40])
a2 = np.array([0,30,40])
print('campare each value of a1 with a2')
print(np.in1d(a1,a2))
               

campare each value of a1 with a2
[False False  True  True]


In [94]:
#Write a NumPy program to find common values between two arrays.
a1 = np.array([10,20,30,40])
a2 = np.array([0,30,40])
print('common values between two arrays')
print(np.intersect1d(a1,a2))

common values between two arrays
[30 40]


In [95]:
#Write a NumPy program to get the unique elements of an array.
a1 = np.array([10,20,30,40])
a2 = np.array([0,30,40])
print('unique value from a1')
print(np.unique(a1))

unique value from a1
[10 20 30 40]


In [96]:
#Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, 
#unique values that are in only one (not both) of the input arrays.
a1 = np.array([10,20,30,40])
a2 = np.array([0,30,40])
print('unique values that are in only one (not both) of the input arrays')
print(np.setxor1d(a1,a2))

unique values that are in only one (not both) of the input arrays
[ 0 10 20]


In [101]:
# Write a NumPy program to find the union of two arrays. Union will return the unique, 
#sorted array of values that are in either of the two input arrays.
a1 = np.array([0,10,30,50])
a2 = np.array([20,40,60])
print('sorted union pf two array:')
print(np.union1d(a1,a2))

sorted union pf two array:
[ 0 10 20 30 40 50 60]


In [103]:
#Write a NumPy program to test whether all elements in an array evaluate to True.
print(np.all([10,20,0,-5]))
print(np.all([10,20,-5]))

False
True


In [107]:
#Write a NumPy program to construct an array by repeating.
a = np.array([1,2,3,4])
print('for repeating 2 times')
print(np.tile(a,2))
print('for repeating 3 times')
print(np.tile(a,3))

for repeating 2 times
[1 2 3 4 1 2 3 4]
for repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


In [110]:
# Write a NumPy program to repeat elements of an array.
x= np.repeat(3,4)
print(x)
print(np.repeat(a,2))

[3 3 3 3]
[1 1 2 2 3 3 4 4]


In [112]:
#Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array. 
a
print('maximum value', np.argmax(a))
print('minimum value',np.argmin(a))

maximum value 3
minimum value 0


In [119]:
#Write a NumPy program to sort an along the first, last axis of an array.
a = np.array([[4,6],[2,1]])
a
print('along the first axis',np.sort(a,axis=0))
print('along the last axis', np.sort(a,axis=1))


along the first axis [[2 1]
 [4 6]]
along the last axis [[4 6]
 [1 2]]


In [127]:
#Write a NumPy program to sort pairs of first name and last name return their indices.
first_name = ('Amit', 'Pooja','Neeta')
last_name =('Jadhav', 'Sawant','Patil')
x = np.lexsort((first_name,last_name))
[first_name[i]+ ' '+last_name[i] for i in x]

['Amit Jadhav', 'Neeta Patil', 'Pooja Sawant']

In [134]:
#. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in
x = np.array([[0,10,20],[30,40,50]])
print(x)
print('values bigger than 10',x[x>10])
print('there indices', np.nonzero(x>10))



[[ 0 10 20]
 [30 40 50]]
values bigger than 10 [20 30 40 50]
there indices (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [147]:
# Write a NumPy program to save a NumPy array to a text file
a = np.arange(10.0,200.0,10)
x = np.savetxt('file',a,delimiter=',')
a

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110.,
       120., 130., 140., 150., 160., 170., 180., 190.])

In [156]:
# Write a NumPy program to find the memory size of a NumPy array
a = np.zeros((4,3))

print('%d bytes'% (a.size*a.itemsize))

96 bytes


In [158]:
a
a.reshape((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [159]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [161]:
x = np.ravel(a)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [175]:

b = np.arange(0,9).reshape(3,3)
print(type(b))
print(b.shape)
print(b.size)

<class 'numpy.ndarray'>
(3, 3)
9


In [1]:
import numpy as np

In [7]:
#Write a NumPy program to change the data type of an array.
a= np.array([[2,4,6],[6,8,10]],dtype = 'int32')
a
    

array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [10]:
x =a.astype(float)
x

array([[ 2.,  4.,  6.],
       [ 6.,  8., 10.]])

In [19]:
#Write a NumPy program to create a new array of 3*5, filled with 2
a = np.ones((3,5),dtype=int)*2
a

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [27]:
#Write a NumPy program to create an array of 10's with the same shape and type of a given
a = np.arange(4,dtype=int)
x = np.full_like(a,10)
x

array([10, 10, 10, 10])

In [44]:
#Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere.
a = np.diagflat([1,1,1])
a



array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
# Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
a = np.diagflat([4,5,6,8])
a

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [49]:
#Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50.
a = np.arange(0,51)
print(a)
b = np.arange(10,51)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [55]:
# Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive
a = np.linspace((2.5),(6.5),num=30)
a

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

In [67]:
#Write a NumPy program to create an array which looks like below array
a = np.tri(4,3,-1,dtype=int)
a

array([[0, 0, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [72]:
#Write a NumPy program to create an array which looks like below array.
a = np.triu(np.arange(2,14).reshape(4,3),-1)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 0,  9, 10],
       [ 0,  0, 13]])

In [73]:
#Write a NumPy program to collapse a 3-D array into one dimension array.
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 0,  9, 10],
       [ 0,  0, 13]])

In [74]:
a.ravel()

array([ 2,  3,  4,  5,  6,  7,  0,  9, 10,  0,  0, 13])

In [79]:
#Write a NumPy program to find the 4th element of a specified array.
a = np.array([[2,4,6],[6,8,10]])
a

array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [88]:
a[-1:2,0]

array([6])

In [99]:
#Write a NumPy program to interchange two axes of an array.
a =np.array ([[1,2,3]])
print(a)
b = np.swapaxes(a,0,1)
print(b)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [113]:
#Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.

a= np.zeros((2,3,4))
print(a)
x = (np.moveaxis(a,-1,0).shape)
print(x)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(4, 2, 3)
